### ISSUE TITLE
Generate .mdx files instead of .md

### ISSUE THREAD

**Issue by acossta** [synx-ai/openapi2md#1]
Generating .mdx files would play nicer with docusaurus that prefers them.

> While both .md and .mdx files are parsed using MDX, some of the syntax are treated slightly differently. For the most accurate parsing and better editor support, we recommend using the .mdx extension for files containing MDX syntax.

**Comment by carlosrivera** [comment]
@acossta I totally missed that, not sure what would be the best way to solve this, we can either:

a) just to write a default `.mdx` extension, or 
b) allow the user to specify their preferred extension 

I personally like the latter, as the the generator can be used to write anything specified in the templates, like a `.js` for an actual API. 

What do you think? Would you like to send a PR?

**Comment by carlosrivera** [comment]
Already fixed :) thank you for the suggestion!
