### ISSUE TITLE
Add an explicit dependency on js-yaml

### ISSUE THREAD

**Issue by markandrus** [synx-ai/openapi2md#2]
`oas3-mdx` uses `safeLoad` from `js-yaml` [here](https://github.com/synx-ai/oas3-mdx/blob/aaab7b2672e3e90e66a7d4321d930fab3cd5e0d3/src/bundler.ts#L100). That API was renamed to `load` in `js-yaml` 4.x (see [here](https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md)).

It seems that `oas3-mdx` currently depends on `js-yaml` transitively via `json-schema-ref-parser` &rarr; `@apidevtools/json-schema-ref-parser` &rarr; `js-yaml`.

`@apidevtools/json-schema-ref-parser` updated to js-yaml 4.x in https://github.com/APIDevTools/json-schema-ref-parser/pull/235, and now new installs of `oas3-mdx` are broken.

We should either

* Add an explicit dependency on `js-yaml` 3.x, or
* Add an explicit dependency on `js-yaml` 4.x and make `oas3-mdx` compatible with `js-yaml` 4.x.

**Comment by carlosrivera** [comment]
Woha! Thank you for this fix.
